### ISSUE TITLE
CORS issues

### ISSUE THREAD

**Issue by nguyenhuucam91** [nguyentienphuc/feeds#3]
Chưa handle được CORS ở một số trang, với trang Vietnamnet thì ko vấn đề gì vì CORS disabled, tuy nhiên với vnexpress hay trang reuters thì vẫn bị CORS
![capture](https://cloud.githubusercontent.com/assets/4926260/21960171/288d931c-db13-11e6-8e0f-e75b6fca7d4a.PNG)

**Comment by nguyentienphuc** [comment]
it is not an issue

issue is a bug or a feature to implement

it is not a technical problem

u can add comment to your issue #1
